paths:
  data_root: data
  image_root: ${paths.data_root}/raw
  annotation_root: ${paths.data_root}/curated
  processed_root: ${paths.data_root}/processed
  datasets_root: ${paths.data_root}/datasets
  train_images_dir: ${paths.image_root}/train_images
  test_images_dir: ${paths.image_root}/test_images
  annotation_source_dir: ${paths.annotation_root}/train_annotations

model: runs/exp18_train_yolo11s_res1280/weights/best.pt
imgsz: 1280
conf: 0.25
iou: 0.7
output: submission/exp18_yolo11s_res1280.csv
data: data/datasets/yolo/copy_paste/cp_t20_data_seed42/dataset.yaml
save_config: true
