conf: 0.25
data: data/datasets/yolo/copy_paste/cp_t20_data_seed42/dataset.yaml
imgsz: 960
iou: 0.7
json_dir: /home/imella0707/PillaTech_team04/data/raw/sprint_ai_project1_data/train_annotations
model: runs/exp27S123_train_yolo11s_res960_hsvh020_mosaic00/weights/best.pt
output: submission/exp27_s123_img960.csv
save_config: true
save_log: false
test_images: /home/imella0707/PillaTech_team04/data/raw/sprint_ai_project1_data/test_images
