paths:
  data_root: data
  image_root: ${paths.data_root}/raw
  annotation_root: ${paths.data_root}/curated
  processed_root: ${paths.data_root}/processed
  datasets_root: ${paths.data_root}/datasets
  train_images_dir: ${paths.image_root}/train_images
  test_images_dir: ${paths.image_root}/test_images
  annotation_source_dir: ${paths.annotation_root}/train_annotations

name: "exp15_train_baseline_yolo11s_2.0"
model: "yolo11s.pt"
data: "data/datasets/yolo/copy_paste/cp_t20_data_seed42/dataset.yaml"
epochs: 50
imgsz: 960
batch: 16
workers: 8
patience: 100
amp: true
close_mosaic: 10

# Optimization
# Exp12(auto)의 실제 적용값(applied)을 baseline 고정값으로 명시
optimizer: "AdamW"
lr0: 0.000167
lrf: 0.01
momentum: 0.9
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.0
cos_lr: true
pretrained: true
resume: false

# Augmentation 
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
fliplr: 0.0
flipud: 0.0
degrees: 0.0
mosaic: 1.0
copy_paste: 0.0
mixup: 0.0
erasing: 0.4
auto_augment: "randaugment"

# 재현성 보장
seed: 42
deterministic: true

# Device
device: "0"
