paths:
  data_root: data
  image_root: ${paths.data_root}/raw
  annotation_root: ${paths.data_root}/curated
  processed_root: ${paths.data_root}/processed
  datasets_root: ${paths.data_root}/datasets
  train_images_dir: ${paths.image_root}/train_images
  test_images_dir: ${paths.image_root}/test_images
  annotation_source_dir: ${paths.annotation_root}/train_annotations

data: data/datasets/yolo/copy_paste/cp_t20_data_seed42/dataset.yaml
model: yolo11s.pt
epochs: 50
imgsz: 1024
batch: 16
name: pill_exp7_yolo11s_final
device: "0"

# Augmentations
fliplr: 0.0
flipud: 0.0
degrees: 0.0
mosaic: 1.0
